export const INSERT_PRODUCT = 'INSERT_PRODUCT';
export const INSERT_PRODUCT_SUCCESS = 'INSERT_PRODUCT_SUCCESS';
export const INSERT_PRODUCT_FAILURE = 'INSERT_PRODUCT_FAILURE';
export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS';
